kind: Service
apiVersion: v1
metadata:
  namespace: kubernetes-example
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: NodePort
