kind: Service
apiVersion: v1
metadata:
  namespace: kubernetes-example
  name: redis-replica
  labels:
    app: redis
    role: replica
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: replica
