kind: Service
apiVersion: v1
metadata:
  namespace: kubernetes-example
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master
