apiVersion: v1
kind: Service
metadata:
  name: kubernetes-example-php
  name: redis-replica
  labels:
    app: redis
    role: replica
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: replica
    tier: backend
